### ISSUE TITLE
Looking for new mantainers

### ISSUE THREAD

**Issue by gunta** [gunta/grunt-manifest#48]
Hi everyone! 
It's official: 

I found I couldn't find the time to maintain this repository anymore (also not using Grunt, nor Cache Manifest anymore), 
so I'm looking for new maintainers. 

Anyone ready up to the task, 
wanting to commit to it in the long term?

**Comment by gunta** [comment]
Long time without updating...
Fortunately the company I'm working it now supports working on open source, so I can get time to keep updating the repository.

I've also added @stephanebachelier as a collaborator.

Thank you!

**Comment by stephanebachelier** [comment]
@gunta would it be possible to be added as a npm colloborator too ?

**Comment by gunta** [comment]
@stephanebachelier can you give me your NPM username?

**Comment by stephanebachelier** [comment]
@gunta my NPM username is stephane.bachelier

**Comment by gunta** [comment]
@stephanebachelier added
