### ISSUE TITLE
Not latest version committed to npmjs

### ISSUE THREAD

**Issue by matthieusieben** [gunta/grunt-manifest#56]
Hey, I don't know if it is your responsibility but the latest version of this package on npmjs.com is 0.4.0.

**Comment by ben-crowhurst** [comment]
Well we just lost a morning to this issue!

Please at least state **npm install grunt-manifest --save-dev** will not install the version applicable to the following documentation.

**Comment by samiconductor** [comment]
Is there any reason you are not publishing the latest version to npm? It has a few features we need and we're are having to use a git url to depend on the latest version.

Also, +1 on getting burned by documentation not matching published version.

Let us know if there's anything we can do to help get the latest version published to npm.

**Comment by erikkemperman** [comment]
Same here, would love to see latest version on npmjs... For what it's worth, wgetting the `tasks/manifest.js` file into my local `node_modules/grunt-manifest/tasks` seems to at least fix my immediate problem of the hash feature not working in the current version from npmjs.

**Comment by matthieusieben** [comment]
A cleaner way is to use:
```js
   "grunt-manifest": "git://github.com/gunta/grunt-manifest.git#0.4.2",
```
in you package.json

**Comment by toupeira** [comment]
@gunta please respond :)

**Comment by maboiteaspam** [comment]
@gunta ?

**Comment by stephanebachelier** [comment]
@maboiteaspam I can't publish the new release to npm. Only a contributor for this git repository.

At least you can still follow the advice from @matthieusieben and using the tag.

**Comment by gunta** [comment]
Sorry for the big delay. Updated now.

**Comment by samiconductor** [comment]
Woo! Thanks.

**Comment by maboiteaspam** [comment]
@stephanebachelier yes, thanks, is it what i did in a short. Let s say it is preferable to rely on published  npm package.

@gunta thank you !

**Comment by stephanebachelier** [comment]
@maboiteaspam we agree :)
